Add: use systemd mechanism, if possible.

diff --git a/templates/consul_exporter.sysvinit.redhat.sh.j2 b/templates/consul_exporter.sysvinit.redhat.sh.j2
--- a/templates/consul_exporter.sysvinit.redhat.sh.j2
+++ b/templates/consul_exporter.sysvinit.redhat.sh.j2
@@ -57,6 +57,22 @@ service_checks() {
   if [ "$START" != "yes" ]; then
     service_not_configured $1
   fi
+
+  # Prepare directories
+  mkdir -p "{{ prometheus_pid_path }}" "{{ prometheus_log_path }}"
+  chown -R $USER "{{ prometheus_pid_path }}" "{{ prometheus_log_path }}"
+
+  # Check if PID exists
+  if [ -f "$PID" ]; then
+    PID_NUMBER=`cat $PID`
+    if [ -z "`ps axf | grep ${PID_NUMBER} | grep -v grep`" ]; then
+      echo "Service was aborted abnormally; clean the PID file and continue..."
+      rm -f "$PID"
+    else
+      echo "Service already started; skip..."
+      exit 1
+    fi
+  fi
 }
 
 start() {
